# Generated by Django 5.0.3 on 2024-03-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="update",
            new_name="updated",
        ),
    ]
